Wip test rolling enablement
cloudfoundry-incubator/bits-service-release pull request #6
Opened 2017-04-21 10:17 UTC by idev4u

I have documented the test for the rolling update. Please verify, thanks.

2017-04-21 12:49 UTC, petergtz requested changes
Overall, good document. What I'm missing is an explanation of the overall strategy and why this will prove that it works. The Test description section only describes what has been done, but not why.

Note that it is quite difficult to read the document because github can't render the markdown correctly due to some errors in indentation and spacing (I've commented on those).

While going through the document, I've also marked little typos, when I saw some.

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +##Steps
`## Steps` --> missing space

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +		 - name: cf1
wrong indentation

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +	```yaml
Remove indentation

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +2. Push an app for example `cf push my-awesome-app` [here](### crete the dummy-app) is a the _"how to"_ for createing the app.
1. `create`
2. a/the

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +4. Scale the app and see whats happend for CC without bits-service
what has happened

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +Expected result is, 28 request to blobstore. Additionally you should see the ip from CC1 and CC2 in the log file of the blobstore `output`.
Why 28?

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +6. Enable the bits service for one CC and repaet the steps.
repeat

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +# Issues Found
Somehow this whole section is rendered verbatim. Please check why.

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +**Verifaction:**
Verification

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +Repaet this test with CC1 and CC2 bits-service _ENABLED_.
`Repeat` here and below

2017-04-21 12:49 UTC, petergtz commented on test/test_rolling_enablement_of_bits-service.md
> +Server error, status code: 503, error code: 150003, message: One or more instances could not be started because of insufficient running resources.
Is this error coming from the CC or from the blobstore?

2017-04-27 12:08 UTC, suhlig approved these changes
Nice work, thank you!

2017-04-27 12:13 UTC, merged